apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-persist
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.200.19
    path: /home/k8s-data/grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-persist
  namespace: grafana
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi