apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - name: "web"
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30001
  selector:
    app: grafana-dep
status:
  loadBalancer: {}
